check assignment:
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^student\/.+/
  stage: test
  parallel:
    matrix:
    - SESSION_NAME:
      - course introduction
      - use container images
      - evolve a container image
      - build with dockerfile
      - build with multi stage
      - networking
      - persistence
  trigger:
    include:
    - local: $SESSION_NAME/homework/.gitlab-ci.yml
    strategy: depend
  variables:
    ASSIGNMENT_WORKDIR: $SESSION_NAME/homework
