check assignment:
  rules:
  - if: >
      $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      && $CI_COMMIT_BRANCH !~ /^develop\/.+/
  stage: test
  parallel:
    matrix:
    - SESSION_NAME:
      - course introduction
  trigger:
    include:
    - local: $SESSION_NAME/homework/.gitlab-ci.yml
    strategy: depend
  variables:
    ASSIGNMENT_WORKDIR: $SESSION_NAME/homework
