FROM scratch

ONBUILD ARG \
  BUILD_DATE \
  ORGANISATION=Capgemini \
  VCS_REF \
  VCS_URL

ONBUILD LABEL \
	org.opencontainers.image.created=${BUILD_DATE} \
	org.opencontainers.image.revision=${VCS_REF} \
	org.opencontainers.image.source=${VCS_URL} \
	org.opencontainers.image.vendor=${ORGANISATION}

