FROM alpine AS build

RUN apk add \
  binutils \
  py3-pip

RUN pip install pyinstaller --break-system-packages

COPY hello.py /src/

RUN pyinstaller --onefile /src/hello.py

FROM alpine

COPY --from=build /dist/hello /bin/hello

ENTRYPOINT [ "/bin/hello" ]
