FROM busybox

ARG BUILD_DATE
ARG ORGANISATION=Capgemini
ARG VCS_REF
ARG VCS_URL

LABEL \
	org.opencontainers.image.authors=eduard.a.yablonskyi@capgemini.com \
	org.opencontainers.image.created=${BUILD_DATE} \
	org.opencontainers.image.revision=${VCS_REF} \
	org.opencontainers.image.source=${VCS_URL} \
	org.opencontainers.image.vendor=${ORGANISATION}

